[[libevent]]
arch = "aarch64"
git-tree-sha1 = "59b70cd3466b622dd7657d219498cb8ed4fb2a7f"
os = "macos"

    [[libevent.download]]
    sha256 = "c1a5de892b140704baadb21b49706dfe474eaf7db57727d39e3d302011830431"
    url = "https://github.com/JuliaBinaryWrappers/libevent_jll.jl/releases/download/libevent-v2.1.12+0/libevent.v2.1.12.aarch64-apple-darwin.tar.gz"
[[libevent]]
arch = "aarch64"
git-tree-sha1 = "1860817cf94529396ab040920f3647b1048a6cad"
libc = "glibc"
os = "linux"

    [[libevent.download]]
    sha256 = "f55efbadc4c668cb006520fdc910eef7b0c268fbcbb91b2eaceb7f0b3528104c"
    url = "https://github.com/JuliaBinaryWrappers/libevent_jll.jl/releases/download/libevent-v2.1.12+0/libevent.v2.1.12.aarch64-linux-gnu.tar.gz"
[[libevent]]
arch = "aarch64"
git-tree-sha1 = "d9476f1cc42e299fc111225df95581c3e804b420"
libc = "musl"
os = "linux"

    [[libevent.download]]
    sha256 = "185f90439590ec0aaee1efb405795ca749ebe1488a4b23515e42493e474c6a31"
    url = "https://github.com/JuliaBinaryWrappers/libevent_jll.jl/releases/download/libevent-v2.1.12+0/libevent.v2.1.12.aarch64-linux-musl.tar.gz"
[[libevent]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "bb719f62f32745983ddfedae03e4df45e89eda32"
libc = "glibc"
os = "linux"

    [[libevent.download]]
    sha256 = "73f78041eb26a75024865baaa0fb3dd8990fb62cbe3d09b999589a034dc036d5"
    url = "https://github.com/JuliaBinaryWrappers/libevent_jll.jl/releases/download/libevent-v2.1.12+0/libevent.v2.1.12.armv6l-linux-gnueabihf.tar.gz"
[[libevent]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1046c207eb39832ce1cb9568b2a71009687e248d"
libc = "musl"
os = "linux"

    [[libevent.download]]
    sha256 = "aba7f13cc5e3645a03b7951a1c56c67338a2827f06d8f3b96859c0187dcb924a"
    url = "https://github.com/JuliaBinaryWrappers/libevent_jll.jl/releases/download/libevent-v2.1.12+0/libevent.v2.1.12.armv6l-linux-musleabihf.tar.gz"
[[libevent]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ce53a8dcfe3f7918b9dfd85382be5f4d53b2ff6d"
libc = "glibc"
os = "linux"

    [[libevent.download]]
    sha256 = "8aae604ad0edfdcbb487e6af5b6499cc34a0c90ed9cb52aa779283017b645062"
    url = "https://github.com/JuliaBinaryWrappers/libevent_jll.jl/releases/download/libevent-v2.1.12+0/libevent.v2.1.12.armv7l-linux-gnueabihf.tar.gz"
[[libevent]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "72150c26e28f41772cb9204751b0da8f7606c8b5"
libc = "musl"
os = "linux"

    [[libevent.download]]
    sha256 = "c6e2551e7feb6c1076715d1265fce3b5aacc15dd18f304feeda42c89309104bd"
    url = "https://github.com/JuliaBinaryWrappers/libevent_jll.jl/releases/download/libevent-v2.1.12+0/libevent.v2.1.12.armv7l-linux-musleabihf.tar.gz"
[[libevent]]
arch = "i686"
git-tree-sha1 = "89a4591ae1fb54d2a2227d3172e6d3ec8881e78f"
libc = "glibc"
os = "linux"

    [[libevent.download]]
    sha256 = "ed1ffb8b3b2faac8ad35aff160e7ae2818bdff6d975e0d18ce1009759dd333b2"
    url = "https://github.com/JuliaBinaryWrappers/libevent_jll.jl/releases/download/libevent-v2.1.12+0/libevent.v2.1.12.i686-linux-gnu.tar.gz"
[[libevent]]
arch = "i686"
git-tree-sha1 = "500a8906be6b52a11a256352b3da4372f5f1cffd"
libc = "musl"
os = "linux"

    [[libevent.download]]
    sha256 = "c98bfdd2a8d2585305c3c1006aeb128c461c5bbb40890c1a98dd3c9e78d9ff85"
    url = "https://github.com/JuliaBinaryWrappers/libevent_jll.jl/releases/download/libevent-v2.1.12+0/libevent.v2.1.12.i686-linux-musl.tar.gz"
[[libevent]]
arch = "i686"
git-tree-sha1 = "900f7ce53a825f3731bc73de60164755e4fbff33"
os = "windows"

    [[libevent.download]]
    sha256 = "ba821fd5d9772607c8c25ca1ffc792231c4b48b66a44911e227f76e8dd401273"
    url = "https://github.com/JuliaBinaryWrappers/libevent_jll.jl/releases/download/libevent-v2.1.12+0/libevent.v2.1.12.i686-w64-mingw32.tar.gz"
[[libevent]]
arch = "powerpc64le"
git-tree-sha1 = "026233320d59d00f3812bacf104b14fcb7830bb5"
libc = "glibc"
os = "linux"

    [[libevent.download]]
    sha256 = "dced4a741f4ade303b10238d4f48ac4b77c1f415c0f2d9fb6e40dace1513f949"
    url = "https://github.com/JuliaBinaryWrappers/libevent_jll.jl/releases/download/libevent-v2.1.12+0/libevent.v2.1.12.powerpc64le-linux-gnu.tar.gz"
[[libevent]]
arch = "x86_64"
git-tree-sha1 = "2b97790685a39426a473cf20d9e4e7d4c28252dd"
os = "macos"

    [[libevent.download]]
    sha256 = "976517453a8882fecef73ad2f6a3e71664d67c709eea82c33456ef9b492a383a"
    url = "https://github.com/JuliaBinaryWrappers/libevent_jll.jl/releases/download/libevent-v2.1.12+0/libevent.v2.1.12.x86_64-apple-darwin.tar.gz"
[[libevent]]
arch = "x86_64"
git-tree-sha1 = "32435ccbc7affbd03ca9ecc3061735e3b5246435"
libc = "glibc"
os = "linux"

    [[libevent.download]]
    sha256 = "0ab8b3f74da34befcdcb885fe26597550b509ab12df06117bd11857d9bf7b277"
    url = "https://github.com/JuliaBinaryWrappers/libevent_jll.jl/releases/download/libevent-v2.1.12+0/libevent.v2.1.12.x86_64-linux-gnu.tar.gz"
[[libevent]]
arch = "x86_64"
git-tree-sha1 = "1ab8c578d28a3c43d833223706bdc506ea5938d7"
libc = "musl"
os = "linux"

    [[libevent.download]]
    sha256 = "c787b24672bb3b5ada1cd22aba0dbf74761488522dd1c46f9ab7ea04a33d7c6b"
    url = "https://github.com/JuliaBinaryWrappers/libevent_jll.jl/releases/download/libevent-v2.1.12+0/libevent.v2.1.12.x86_64-linux-musl.tar.gz"
[[libevent]]
arch = "x86_64"
git-tree-sha1 = "be57a0e253eddac7a5403eb065b02fa26a473b26"
os = "freebsd"

    [[libevent.download]]
    sha256 = "a5011e33333d40b880b1c8c4bbd3f00b8de3e6f45c9af73f7cc073f643180d3d"
    url = "https://github.com/JuliaBinaryWrappers/libevent_jll.jl/releases/download/libevent-v2.1.12+0/libevent.v2.1.12.x86_64-unknown-freebsd.tar.gz"
[[libevent]]
arch = "x86_64"
git-tree-sha1 = "c98c97667ef974653c650475627994ab1add7f94"
os = "windows"

    [[libevent.download]]
    sha256 = "317207f9ff94203120d68bd88b74285cb29507a41d00fbe746b2994ed20056e2"
    url = "https://github.com/JuliaBinaryWrappers/libevent_jll.jl/releases/download/libevent-v2.1.12+0/libevent.v2.1.12.x86_64-w64-mingw32.tar.gz"
