# Autogenerated wrapper script for libevent_jll for aarch64-apple-darwin
export libevent, libevent_core, libevent_pthreads

using OpenSSL_jll
JLLWrappers.@generate_wrapper_header("libevent")
JLLWrappers.@declare_library_product(libevent, "@rpath/libevent-2.1.7.dylib")
JLLWrappers.@declare_library_product(libevent_core, "@rpath/libevent_core-2.1.7.dylib")
JLLWrappers.@declare_library_product(libevent_pthreads, "@rpath/libevent_pthreads-2.1.7.dylib")
function __init__()
    JLLWrappers.@generate_init_header(OpenSSL_jll)
    JLLWrappers.@init_library_product(
        libevent,
        "lib/libevent.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libevent_core,
        "lib/libevent_core.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libevent_pthreads,
        "lib/libevent_pthreads.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
