# Autogenerated wrapper script for libevent_jll for x86_64-w64-mingw32
export libevent, libevent_core

using OpenSSL_jll
JLLWrappers.@generate_wrapper_header("libevent")
JLLWrappers.@declare_library_product(libevent, "libevent-2-1-7.dll")
JLLWrappers.@declare_library_product(libevent_core, "libevent_core-2-1-7.dll")
function __init__()
    JLLWrappers.@generate_init_header(OpenSSL_jll)
    JLLWrappers.@init_library_product(
        libevent,
        "bin\\libevent-2-1-7.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libevent_core,
        "bin\\libevent_core-2-1-7.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
